# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from billing.v1 import billing_pb2 as billing_dot_v1_dot_billing__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in billing/v1/billing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BillingServiceStub(object):
    """BillingService 积分计费服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCreditBalance = channel.unary_unary(
                '/billing.v1.BillingService/GetCreditBalance',
                request_serializer=billing_dot_v1_dot_billing__pb2.GetCreditBalanceRequest.SerializeToString,
                response_deserializer=billing_dot_v1_dot_billing__pb2.GetCreditBalanceResponse.FromString,
                _registered_method=True)
        self.DeductCredits = channel.unary_unary(
                '/billing.v1.BillingService/DeductCredits',
                request_serializer=billing_dot_v1_dot_billing__pb2.DeductCreditsRequest.SerializeToString,
                response_deserializer=billing_dot_v1_dot_billing__pb2.DeductCreditsResponse.FromString,
                _registered_method=True)
        self.AddCredits = channel.unary_unary(
                '/billing.v1.BillingService/AddCredits',
                request_serializer=billing_dot_v1_dot_billing__pb2.AddCreditsRequest.SerializeToString,
                response_deserializer=billing_dot_v1_dot_billing__pb2.AddCreditsResponse.FromString,
                _registered_method=True)
        self.GetTransactionHistory = channel.unary_unary(
                '/billing.v1.BillingService/GetTransactionHistory',
                request_serializer=billing_dot_v1_dot_billing__pb2.GetTransactionHistoryRequest.SerializeToString,
                response_deserializer=billing_dot_v1_dot_billing__pb2.GetTransactionHistoryResponse.FromString,
                _registered_method=True)
        self.GetUsageStats = channel.unary_unary(
                '/billing.v1.BillingService/GetUsageStats',
                request_serializer=billing_dot_v1_dot_billing__pb2.GetUsageStatsRequest.SerializeToString,
                response_deserializer=billing_dot_v1_dot_billing__pb2.GetUsageStatsResponse.FromString,
                _registered_method=True)


class BillingServiceServicer(object):
    """BillingService 积分计费服务
    """

    def GetCreditBalance(self, request, context):
        """GetCreditBalance 获取积分余额
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeductCredits(self, request, context):
        """DeductCredits 扣除积分
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddCredits(self, request, context):
        """AddCredits 充值积分
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransactionHistory(self, request, context):
        """GetTransactionHistory 获取交易历史
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsageStats(self, request, context):
        """GetUsageStats 获取使用统计
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BillingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCreditBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCreditBalance,
                    request_deserializer=billing_dot_v1_dot_billing__pb2.GetCreditBalanceRequest.FromString,
                    response_serializer=billing_dot_v1_dot_billing__pb2.GetCreditBalanceResponse.SerializeToString,
            ),
            'DeductCredits': grpc.unary_unary_rpc_method_handler(
                    servicer.DeductCredits,
                    request_deserializer=billing_dot_v1_dot_billing__pb2.DeductCreditsRequest.FromString,
                    response_serializer=billing_dot_v1_dot_billing__pb2.DeductCreditsResponse.SerializeToString,
            ),
            'AddCredits': grpc.unary_unary_rpc_method_handler(
                    servicer.AddCredits,
                    request_deserializer=billing_dot_v1_dot_billing__pb2.AddCreditsRequest.FromString,
                    response_serializer=billing_dot_v1_dot_billing__pb2.AddCreditsResponse.SerializeToString,
            ),
            'GetTransactionHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransactionHistory,
                    request_deserializer=billing_dot_v1_dot_billing__pb2.GetTransactionHistoryRequest.FromString,
                    response_serializer=billing_dot_v1_dot_billing__pb2.GetTransactionHistoryResponse.SerializeToString,
            ),
            'GetUsageStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsageStats,
                    request_deserializer=billing_dot_v1_dot_billing__pb2.GetUsageStatsRequest.FromString,
                    response_serializer=billing_dot_v1_dot_billing__pb2.GetUsageStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'billing.v1.BillingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('billing.v1.BillingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BillingService(object):
    """BillingService 积分计费服务
    """

    @staticmethod
    def GetCreditBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/billing.v1.BillingService/GetCreditBalance',
            billing_dot_v1_dot_billing__pb2.GetCreditBalanceRequest.SerializeToString,
            billing_dot_v1_dot_billing__pb2.GetCreditBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeductCredits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/billing.v1.BillingService/DeductCredits',
            billing_dot_v1_dot_billing__pb2.DeductCreditsRequest.SerializeToString,
            billing_dot_v1_dot_billing__pb2.DeductCreditsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddCredits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/billing.v1.BillingService/AddCredits',
            billing_dot_v1_dot_billing__pb2.AddCreditsRequest.SerializeToString,
            billing_dot_v1_dot_billing__pb2.AddCreditsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransactionHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/billing.v1.BillingService/GetTransactionHistory',
            billing_dot_v1_dot_billing__pb2.GetTransactionHistoryRequest.SerializeToString,
            billing_dot_v1_dot_billing__pb2.GetTransactionHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsageStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/billing.v1.BillingService/GetUsageStats',
            billing_dot_v1_dot_billing__pb2.GetUsageStatsRequest.SerializeToString,
            billing_dot_v1_dot_billing__pb2.GetUsageStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
