# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from character.v1 import character_pb2 as character_dot_v1_dot_character__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in character/v1/character_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CharacterServiceStub(object):
    """CharacterService AI角色管理服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCharacter = channel.unary_unary(
                '/character.v1.CharacterService/CreateCharacter',
                request_serializer=character_dot_v1_dot_character__pb2.CreateCharacterRequest.SerializeToString,
                response_deserializer=character_dot_v1_dot_character__pb2.CreateCharacterResponse.FromString,
                _registered_method=True)
        self.UpdateCharacter = channel.unary_unary(
                '/character.v1.CharacterService/UpdateCharacter',
                request_serializer=character_dot_v1_dot_character__pb2.UpdateCharacterRequest.SerializeToString,
                response_deserializer=character_dot_v1_dot_character__pb2.UpdateCharacterResponse.FromString,
                _registered_method=True)
        self.DeleteCharacter = channel.unary_unary(
                '/character.v1.CharacterService/DeleteCharacter',
                request_serializer=character_dot_v1_dot_character__pb2.DeleteCharacterRequest.SerializeToString,
                response_deserializer=character_dot_v1_dot_character__pb2.DeleteCharacterResponse.FromString,
                _registered_method=True)
        self.GetCharacter = channel.unary_unary(
                '/character.v1.CharacterService/GetCharacter',
                request_serializer=character_dot_v1_dot_character__pb2.GetCharacterRequest.SerializeToString,
                response_deserializer=character_dot_v1_dot_character__pb2.GetCharacterResponse.FromString,
                _registered_method=True)
        self.ListCharacters = channel.unary_unary(
                '/character.v1.CharacterService/ListCharacters',
                request_serializer=character_dot_v1_dot_character__pb2.ListCharactersRequest.SerializeToString,
                response_deserializer=character_dot_v1_dot_character__pb2.ListCharactersResponse.FromString,
                _registered_method=True)


class CharacterServiceServicer(object):
    """CharacterService AI角色管理服务
    """

    def CreateCharacter(self, request, context):
        """CreateCharacter 创建角色
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCharacter(self, request, context):
        """UpdateCharacter 更新角色
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCharacter(self, request, context):
        """DeleteCharacter 删除角色
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCharacter(self, request, context):
        """GetCharacter 获取角色详情
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCharacters(self, request, context):
        """ListCharacters 获取角色列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CharacterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCharacter': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCharacter,
                    request_deserializer=character_dot_v1_dot_character__pb2.CreateCharacterRequest.FromString,
                    response_serializer=character_dot_v1_dot_character__pb2.CreateCharacterResponse.SerializeToString,
            ),
            'UpdateCharacter': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCharacter,
                    request_deserializer=character_dot_v1_dot_character__pb2.UpdateCharacterRequest.FromString,
                    response_serializer=character_dot_v1_dot_character__pb2.UpdateCharacterResponse.SerializeToString,
            ),
            'DeleteCharacter': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCharacter,
                    request_deserializer=character_dot_v1_dot_character__pb2.DeleteCharacterRequest.FromString,
                    response_serializer=character_dot_v1_dot_character__pb2.DeleteCharacterResponse.SerializeToString,
            ),
            'GetCharacter': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCharacter,
                    request_deserializer=character_dot_v1_dot_character__pb2.GetCharacterRequest.FromString,
                    response_serializer=character_dot_v1_dot_character__pb2.GetCharacterResponse.SerializeToString,
            ),
            'ListCharacters': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCharacters,
                    request_deserializer=character_dot_v1_dot_character__pb2.ListCharactersRequest.FromString,
                    response_serializer=character_dot_v1_dot_character__pb2.ListCharactersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'character.v1.CharacterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('character.v1.CharacterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CharacterService(object):
    """CharacterService AI角色管理服务
    """

    @staticmethod
    def CreateCharacter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/character.v1.CharacterService/CreateCharacter',
            character_dot_v1_dot_character__pb2.CreateCharacterRequest.SerializeToString,
            character_dot_v1_dot_character__pb2.CreateCharacterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCharacter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/character.v1.CharacterService/UpdateCharacter',
            character_dot_v1_dot_character__pb2.UpdateCharacterRequest.SerializeToString,
            character_dot_v1_dot_character__pb2.UpdateCharacterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCharacter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/character.v1.CharacterService/DeleteCharacter',
            character_dot_v1_dot_character__pb2.DeleteCharacterRequest.SerializeToString,
            character_dot_v1_dot_character__pb2.DeleteCharacterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCharacter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/character.v1.CharacterService/GetCharacter',
            character_dot_v1_dot_character__pb2.GetCharacterRequest.SerializeToString,
            character_dot_v1_dot_character__pb2.GetCharacterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCharacters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/character.v1.CharacterService/ListCharacters',
            character_dot_v1_dot_character__pb2.ListCharactersRequest.SerializeToString,
            character_dot_v1_dot_character__pb2.ListCharactersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
