# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from user.v1 import user_pb2 as user_dot_v1_dot_user__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in user/v1/user_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """UserService 用户认证与管理服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/user.v1.UserService/Register',
                request_serializer=user_dot_v1_dot_user__pb2.RegisterRequest.SerializeToString,
                response_deserializer=user_dot_v1_dot_user__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/user.v1.UserService/Login',
                request_serializer=user_dot_v1_dot_user__pb2.LoginRequest.SerializeToString,
                response_deserializer=user_dot_v1_dot_user__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.RefreshToken = channel.unary_unary(
                '/user.v1.UserService/RefreshToken',
                request_serializer=user_dot_v1_dot_user__pb2.RefreshTokenRequest.SerializeToString,
                response_deserializer=user_dot_v1_dot_user__pb2.RefreshTokenResponse.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/user.v1.UserService/GetUser',
                request_serializer=user_dot_v1_dot_user__pb2.GetUserRequest.SerializeToString,
                response_deserializer=user_dot_v1_dot_user__pb2.GetUserResponse.FromString,
                _registered_method=True)
        self.UpdateProfile = channel.unary_unary(
                '/user.v1.UserService/UpdateProfile',
                request_serializer=user_dot_v1_dot_user__pb2.UpdateProfileRequest.SerializeToString,
                response_deserializer=user_dot_v1_dot_user__pb2.UpdateProfileResponse.FromString,
                _registered_method=True)
        self.DeleteAccount = channel.unary_unary(
                '/user.v1.UserService/DeleteAccount',
                request_serializer=user_dot_v1_dot_user__pb2.DeleteAccountRequest.SerializeToString,
                response_deserializer=user_dot_v1_dot_user__pb2.DeleteAccountResponse.FromString,
                _registered_method=True)
        self.RecoverAccount = channel.unary_unary(
                '/user.v1.UserService/RecoverAccount',
                request_serializer=user_dot_v1_dot_user__pb2.RecoverAccountRequest.SerializeToString,
                response_deserializer=user_dot_v1_dot_user__pb2.RecoverAccountResponse.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """UserService 用户认证与管理服务
    """

    def Register(self, request, context):
        """Register 用户注册
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Login 用户登录
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """RefreshToken 刷新令牌
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """GetUser 获取用户信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProfile(self, request, context):
        """UpdateProfile 更新用户画像
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAccount(self, request, context):
        """DeleteAccount 删除账号(30天冷静期)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecoverAccount(self, request, context):
        """RecoverAccount 恢复账号(冷静期内)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=user_dot_v1_dot_user__pb2.RegisterRequest.FromString,
                    response_serializer=user_dot_v1_dot_user__pb2.RegisterResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=user_dot_v1_dot_user__pb2.LoginRequest.FromString,
                    response_serializer=user_dot_v1_dot_user__pb2.LoginResponse.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=user_dot_v1_dot_user__pb2.RefreshTokenRequest.FromString,
                    response_serializer=user_dot_v1_dot_user__pb2.RefreshTokenResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=user_dot_v1_dot_user__pb2.GetUserRequest.FromString,
                    response_serializer=user_dot_v1_dot_user__pb2.GetUserResponse.SerializeToString,
            ),
            'UpdateProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProfile,
                    request_deserializer=user_dot_v1_dot_user__pb2.UpdateProfileRequest.FromString,
                    response_serializer=user_dot_v1_dot_user__pb2.UpdateProfileResponse.SerializeToString,
            ),
            'DeleteAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAccount,
                    request_deserializer=user_dot_v1_dot_user__pb2.DeleteAccountRequest.FromString,
                    response_serializer=user_dot_v1_dot_user__pb2.DeleteAccountResponse.SerializeToString,
            ),
            'RecoverAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.RecoverAccount,
                    request_deserializer=user_dot_v1_dot_user__pb2.RecoverAccountRequest.FromString,
                    response_serializer=user_dot_v1_dot_user__pb2.RecoverAccountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user.v1.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('user.v1.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """UserService 用户认证与管理服务
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/Register',
            user_dot_v1_dot_user__pb2.RegisterRequest.SerializeToString,
            user_dot_v1_dot_user__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/Login',
            user_dot_v1_dot_user__pb2.LoginRequest.SerializeToString,
            user_dot_v1_dot_user__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/RefreshToken',
            user_dot_v1_dot_user__pb2.RefreshTokenRequest.SerializeToString,
            user_dot_v1_dot_user__pb2.RefreshTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/GetUser',
            user_dot_v1_dot_user__pb2.GetUserRequest.SerializeToString,
            user_dot_v1_dot_user__pb2.GetUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/UpdateProfile',
            user_dot_v1_dot_user__pb2.UpdateProfileRequest.SerializeToString,
            user_dot_v1_dot_user__pb2.UpdateProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/DeleteAccount',
            user_dot_v1_dot_user__pb2.DeleteAccountRequest.SerializeToString,
            user_dot_v1_dot_user__pb2.DeleteAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecoverAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/RecoverAccount',
            user_dot_v1_dot_user__pb2.RecoverAccountRequest.SerializeToString,
            user_dot_v1_dot_user__pb2.RecoverAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
