# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from conversation.v1 import conversation_pb2 as conversation_dot_v1_dot_conversation__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in conversation/v1/conversation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConversationServiceStub(object):
    """ConversationService 对话管理服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateConversation = channel.unary_unary(
                '/conversation.v1.ConversationService/CreateConversation',
                request_serializer=conversation_dot_v1_dot_conversation__pb2.CreateConversationRequest.SerializeToString,
                response_deserializer=conversation_dot_v1_dot_conversation__pb2.CreateConversationResponse.FromString,
                _registered_method=True)
        self.GetConversation = channel.unary_unary(
                '/conversation.v1.ConversationService/GetConversation',
                request_serializer=conversation_dot_v1_dot_conversation__pb2.GetConversationRequest.SerializeToString,
                response_deserializer=conversation_dot_v1_dot_conversation__pb2.GetConversationResponse.FromString,
                _registered_method=True)
        self.ListConversations = channel.unary_unary(
                '/conversation.v1.ConversationService/ListConversations',
                request_serializer=conversation_dot_v1_dot_conversation__pb2.ListConversationsRequest.SerializeToString,
                response_deserializer=conversation_dot_v1_dot_conversation__pb2.ListConversationsResponse.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_unary(
                '/conversation.v1.ConversationService/SendMessage',
                request_serializer=conversation_dot_v1_dot_conversation__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=conversation_dot_v1_dot_conversation__pb2.SendMessageResponse.FromString,
                _registered_method=True)
        self.StreamMessage = channel.unary_stream(
                '/conversation.v1.ConversationService/StreamMessage',
                request_serializer=conversation_dot_v1_dot_conversation__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=conversation_dot_v1_dot_conversation__pb2.MessageChunk.FromString,
                _registered_method=True)
        self.GetMessages = channel.unary_unary(
                '/conversation.v1.ConversationService/GetMessages',
                request_serializer=conversation_dot_v1_dot_conversation__pb2.GetMessagesRequest.SerializeToString,
                response_deserializer=conversation_dot_v1_dot_conversation__pb2.GetMessagesResponse.FromString,
                _registered_method=True)
        self.ArchiveConversation = channel.unary_unary(
                '/conversation.v1.ConversationService/ArchiveConversation',
                request_serializer=conversation_dot_v1_dot_conversation__pb2.ArchiveConversationRequest.SerializeToString,
                response_deserializer=conversation_dot_v1_dot_conversation__pb2.ArchiveConversationResponse.FromString,
                _registered_method=True)
        self.DeleteConversation = channel.unary_unary(
                '/conversation.v1.ConversationService/DeleteConversation',
                request_serializer=conversation_dot_v1_dot_conversation__pb2.DeleteConversationRequest.SerializeToString,
                response_deserializer=conversation_dot_v1_dot_conversation__pb2.DeleteConversationResponse.FromString,
                _registered_method=True)


class ConversationServiceServicer(object):
    """ConversationService 对话管理服务
    """

    def CreateConversation(self, request, context):
        """CreateConversation 创建新对话
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConversation(self, request, context):
        """GetConversation 获取对话详情
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConversations(self, request, context):
        """ListConversations 获取用户的对话列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """SendMessage 发送消息(同步)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMessage(self, request, context):
        """StreamMessage 发送消息(流式)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessages(self, request, context):
        """GetMessages 获取历史消息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ArchiveConversation(self, request, context):
        """ArchiveConversation 归档对话
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteConversation(self, request, context):
        """DeleteConversation 删除对话
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConversationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateConversation,
                    request_deserializer=conversation_dot_v1_dot_conversation__pb2.CreateConversationRequest.FromString,
                    response_serializer=conversation_dot_v1_dot_conversation__pb2.CreateConversationResponse.SerializeToString,
            ),
            'GetConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConversation,
                    request_deserializer=conversation_dot_v1_dot_conversation__pb2.GetConversationRequest.FromString,
                    response_serializer=conversation_dot_v1_dot_conversation__pb2.GetConversationResponse.SerializeToString,
            ),
            'ListConversations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConversations,
                    request_deserializer=conversation_dot_v1_dot_conversation__pb2.ListConversationsRequest.FromString,
                    response_serializer=conversation_dot_v1_dot_conversation__pb2.ListConversationsResponse.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=conversation_dot_v1_dot_conversation__pb2.SendMessageRequest.FromString,
                    response_serializer=conversation_dot_v1_dot_conversation__pb2.SendMessageResponse.SerializeToString,
            ),
            'StreamMessage': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMessage,
                    request_deserializer=conversation_dot_v1_dot_conversation__pb2.SendMessageRequest.FromString,
                    response_serializer=conversation_dot_v1_dot_conversation__pb2.MessageChunk.SerializeToString,
            ),
            'GetMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessages,
                    request_deserializer=conversation_dot_v1_dot_conversation__pb2.GetMessagesRequest.FromString,
                    response_serializer=conversation_dot_v1_dot_conversation__pb2.GetMessagesResponse.SerializeToString,
            ),
            'ArchiveConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.ArchiveConversation,
                    request_deserializer=conversation_dot_v1_dot_conversation__pb2.ArchiveConversationRequest.FromString,
                    response_serializer=conversation_dot_v1_dot_conversation__pb2.ArchiveConversationResponse.SerializeToString,
            ),
            'DeleteConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteConversation,
                    request_deserializer=conversation_dot_v1_dot_conversation__pb2.DeleteConversationRequest.FromString,
                    response_serializer=conversation_dot_v1_dot_conversation__pb2.DeleteConversationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'conversation.v1.ConversationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('conversation.v1.ConversationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConversationService(object):
    """ConversationService 对话管理服务
    """

    @staticmethod
    def CreateConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conversation.v1.ConversationService/CreateConversation',
            conversation_dot_v1_dot_conversation__pb2.CreateConversationRequest.SerializeToString,
            conversation_dot_v1_dot_conversation__pb2.CreateConversationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conversation.v1.ConversationService/GetConversation',
            conversation_dot_v1_dot_conversation__pb2.GetConversationRequest.SerializeToString,
            conversation_dot_v1_dot_conversation__pb2.GetConversationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListConversations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conversation.v1.ConversationService/ListConversations',
            conversation_dot_v1_dot_conversation__pb2.ListConversationsRequest.SerializeToString,
            conversation_dot_v1_dot_conversation__pb2.ListConversationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conversation.v1.ConversationService/SendMessage',
            conversation_dot_v1_dot_conversation__pb2.SendMessageRequest.SerializeToString,
            conversation_dot_v1_dot_conversation__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/conversation.v1.ConversationService/StreamMessage',
            conversation_dot_v1_dot_conversation__pb2.SendMessageRequest.SerializeToString,
            conversation_dot_v1_dot_conversation__pb2.MessageChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conversation.v1.ConversationService/GetMessages',
            conversation_dot_v1_dot_conversation__pb2.GetMessagesRequest.SerializeToString,
            conversation_dot_v1_dot_conversation__pb2.GetMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ArchiveConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conversation.v1.ConversationService/ArchiveConversation',
            conversation_dot_v1_dot_conversation__pb2.ArchiveConversationRequest.SerializeToString,
            conversation_dot_v1_dot_conversation__pb2.ArchiveConversationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conversation.v1.ConversationService/DeleteConversation',
            conversation_dot_v1_dot_conversation__pb2.DeleteConversationRequest.SerializeToString,
            conversation_dot_v1_dot_conversation__pb2.DeleteConversationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
