# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from memory.v1 import memory_pb2 as memory_dot_v1_dot_memory__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in memory/v1/memory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemoryServiceStub(object):
    """MemoryService 记忆存储与检索服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveMemory = channel.unary_unary(
                '/memory.v1.MemoryService/SaveMemory',
                request_serializer=memory_dot_v1_dot_memory__pb2.SaveMemoryRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__pb2.SaveMemoryResponse.FromString,
                _registered_method=True)
        self.RetrieveMemories = channel.unary_unary(
                '/memory.v1.MemoryService/RetrieveMemories',
                request_serializer=memory_dot_v1_dot_memory__pb2.RetrieveMemoriesRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__pb2.RetrieveMemoriesResponse.FromString,
                _registered_method=True)
        self.GetUserPortrait = channel.unary_unary(
                '/memory.v1.MemoryService/GetUserPortrait',
                request_serializer=memory_dot_v1_dot_memory__pb2.GetUserPortraitRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__pb2.GetUserPortraitResponse.FromString,
                _registered_method=True)
        self.UpdateRelationship = channel.unary_unary(
                '/memory.v1.MemoryService/UpdateRelationship',
                request_serializer=memory_dot_v1_dot_memory__pb2.UpdateRelationshipRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__pb2.UpdateRelationshipResponse.FromString,
                _registered_method=True)
        self.GetRelationship = channel.unary_unary(
                '/memory.v1.MemoryService/GetRelationship',
                request_serializer=memory_dot_v1_dot_memory__pb2.GetRelationshipRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__pb2.GetRelationshipResponse.FromString,
                _registered_method=True)
        self.DeleteMemory = channel.unary_unary(
                '/memory.v1.MemoryService/DeleteMemory',
                request_serializer=memory_dot_v1_dot_memory__pb2.DeleteMemoryRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__pb2.DeleteMemoryResponse.FromString,
                _registered_method=True)
        self.DetectContradictions = channel.unary_unary(
                '/memory.v1.MemoryService/DetectContradictions',
                request_serializer=memory_dot_v1_dot_memory__pb2.DetectContradictionsRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__pb2.DetectContradictionsResponse.FromString,
                _registered_method=True)
        self.ReportAuditEvent = channel.unary_unary(
                '/memory.v1.MemoryService/ReportAuditEvent',
                request_serializer=memory_dot_v1_dot_memory__pb2.ReportAuditEventRequest.SerializeToString,
                response_deserializer=memory_dot_v1_dot_memory__pb2.ReportAuditEventResponse.FromString,
                _registered_method=True)


class MemoryServiceServicer(object):
    """MemoryService 记忆存储与检索服务
    """

    def SaveMemory(self, request, context):
        """SaveMemory 保存记忆
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveMemories(self, request, context):
        """RetrieveMemories 检索相关记忆(向量相似度)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserPortrait(self, request, context):
        """GetUserPortrait 获取用户画像
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRelationship(self, request, context):
        """UpdateRelationship 更新关系亲密度
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRelationship(self, request, context):
        """GetRelationship 获取关系状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMemory(self, request, context):
        """DeleteMemory 删除记忆
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectContradictions(self, request, context):
        """DetectContradictions 检测记忆矛盾
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportAuditEvent(self, request, context):
        """ReportAuditEvent 上报审计事件(社区安全/策略审计)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveMemory,
                    request_deserializer=memory_dot_v1_dot_memory__pb2.SaveMemoryRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__pb2.SaveMemoryResponse.SerializeToString,
            ),
            'RetrieveMemories': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveMemories,
                    request_deserializer=memory_dot_v1_dot_memory__pb2.RetrieveMemoriesRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__pb2.RetrieveMemoriesResponse.SerializeToString,
            ),
            'GetUserPortrait': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserPortrait,
                    request_deserializer=memory_dot_v1_dot_memory__pb2.GetUserPortraitRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__pb2.GetUserPortraitResponse.SerializeToString,
            ),
            'UpdateRelationship': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRelationship,
                    request_deserializer=memory_dot_v1_dot_memory__pb2.UpdateRelationshipRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__pb2.UpdateRelationshipResponse.SerializeToString,
            ),
            'GetRelationship': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRelationship,
                    request_deserializer=memory_dot_v1_dot_memory__pb2.GetRelationshipRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__pb2.GetRelationshipResponse.SerializeToString,
            ),
            'DeleteMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMemory,
                    request_deserializer=memory_dot_v1_dot_memory__pb2.DeleteMemoryRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__pb2.DeleteMemoryResponse.SerializeToString,
            ),
            'DetectContradictions': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectContradictions,
                    request_deserializer=memory_dot_v1_dot_memory__pb2.DetectContradictionsRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__pb2.DetectContradictionsResponse.SerializeToString,
            ),
            'ReportAuditEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportAuditEvent,
                    request_deserializer=memory_dot_v1_dot_memory__pb2.ReportAuditEventRequest.FromString,
                    response_serializer=memory_dot_v1_dot_memory__pb2.ReportAuditEventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memory.v1.MemoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memory.v1.MemoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryService(object):
    """MemoryService 记忆存储与检索服务
    """

    @staticmethod
    def SaveMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.MemoryService/SaveMemory',
            memory_dot_v1_dot_memory__pb2.SaveMemoryRequest.SerializeToString,
            memory_dot_v1_dot_memory__pb2.SaveMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveMemories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.MemoryService/RetrieveMemories',
            memory_dot_v1_dot_memory__pb2.RetrieveMemoriesRequest.SerializeToString,
            memory_dot_v1_dot_memory__pb2.RetrieveMemoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserPortrait(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.MemoryService/GetUserPortrait',
            memory_dot_v1_dot_memory__pb2.GetUserPortraitRequest.SerializeToString,
            memory_dot_v1_dot_memory__pb2.GetUserPortraitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRelationship(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.MemoryService/UpdateRelationship',
            memory_dot_v1_dot_memory__pb2.UpdateRelationshipRequest.SerializeToString,
            memory_dot_v1_dot_memory__pb2.UpdateRelationshipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRelationship(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.MemoryService/GetRelationship',
            memory_dot_v1_dot_memory__pb2.GetRelationshipRequest.SerializeToString,
            memory_dot_v1_dot_memory__pb2.GetRelationshipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.MemoryService/DeleteMemory',
            memory_dot_v1_dot_memory__pb2.DeleteMemoryRequest.SerializeToString,
            memory_dot_v1_dot_memory__pb2.DeleteMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectContradictions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.MemoryService/DetectContradictions',
            memory_dot_v1_dot_memory__pb2.DetectContradictionsRequest.SerializeToString,
            memory_dot_v1_dot_memory__pb2.DetectContradictionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportAuditEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.MemoryService/ReportAuditEvent',
            memory_dot_v1_dot_memory__pb2.ReportAuditEventRequest.SerializeToString,
            memory_dot_v1_dot_memory__pb2.ReportAuditEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
